/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ItImageEditor {
    'src': string;
  }
}

declare global {


  interface HTMLItImageEditorElement extends Components.ItImageEditor, HTMLStencilElement {}
  var HTMLItImageEditorElement: {
    prototype: HTMLItImageEditorElement;
    new (): HTMLItImageEditorElement;
  };
  interface HTMLElementTagNameMap {
    'it-image-editor': HTMLItImageEditorElement;
  }
}

declare namespace LocalJSX {
  interface ItImageEditor extends JSXBase.HTMLAttributes<HTMLItImageEditorElement> {
    /**
    * Emitted when the save button is clicked.
    */
    'onSave'?: (event: CustomEvent<{ base64: string }>) => void;
    'src'?: string;
  }

  interface IntrinsicElements {
    'it-image-editor': ItImageEditor;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


